name: FK3 Build & Deploy Workflow

on:
  push:
    branches: [ "FK3" ] #

jobs:
  build-and-push:
    name: Build and Push Docker Imag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to Dockerhub
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      # building docker image using the dockerfile
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/weather-dashboard:latest .

      # pushes image to DockerHub account
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/weather-dashboard:latest
